# Site settings
title: Taylor Smith
description:
baseurl: ""
url: "http://www.tsmithphotos.com"

# Build settings
markdown: kramdown

exclude:
  - source # Don't include the original photos directory
  - node_modules # Apparently this is magic sauce to make Jekyll less super slow
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - '*~'
  - '#*#'
  - GPL.txt # No need for this to be in the site. LICENSE.md is, but not linked anywhere

keep_files:
  - photo # Don't clobber the photo exports directory
  - css   # Don't clobber site CSS, this way I don't have to store compiled CSS
  - js    # Don't clobber site JS, which is built with Gulp and includes Photoswipe
  - gfx   # Don't clobber site graphics/images/assets
  - .htaccess

# Use the ingenuitive "compress.html" HTML minification template from
# https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: [div, ul, section]
  comments: all
  endings: []
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

defaults:
  -
    scope:
      type: posts
    values:
      layout: post

paginate: 10
paginate_path: "/archive/:num/"
permalink: /:year-:month-:day-:title/
