# Site wide configuration

title:            Nathan Birrell
locale:           en_US
# url:              http://localhost:4000
url:              http://nathanbirrell.me

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Nathan Birrell
  avatar: bio-photo.jpg
  bio: "Web/software development contractor for small businesses, located in Melbourne."
  email: "nathanbirrell@gmail.com"
  phone: "0418 636 581"
  location: "Melbourne, VIC"
  location_url: "https://www.google.com.au/maps/place/Melbourne+VIC/"
  disqus-shortname: 
  twitter: "@nathanbirrell"
  # facebook: "nbirrell"
  google:
    # plus: "NathanBirrell"
    analytics: UA-41066869-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: "nathanbirrell"
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: "nathanbirrell"
  xing: #username
  instagram: "nathanbirrell"
  # lastfm: "nathanbirrell"
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: "nbirrell"

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
