# Site settings
title: Nathan Birrell | Digital services for small businesses, Melbourne
email: nathanbirrell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a digital contractor for small businesses in Melbourne. Specialising in the web, I help clients improve their business using technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Nathan Birrell
email: nathanbirrell@gmail.com
facebook_username: nbirrell
twitter_username: nathanbirrell
github_username: nathanbirrell
address: Melbourne, Australia
  # - line:
  # - line:
  # Feel free to add more lines here 
telephone: 0418 636 581
copyright: 2013 - 

# API settings
google_api_key: AIzaSyCbpOUWLrvGrRBT4cmb8yDfVl0ZFpCLUGc

# Build settings
markdown: kramdown